# AUTHOR: toydotgame
# CREATED: 2025-10-21
# jekyll-serve.sh calls this file specifically after _config.yml, whereas the
# production/GH pages build doesn't use that script and therefore doesn't use
# this config.

# BUILD
#incremental:         true
show_drafts:         true
strict_front_matter: true
unpublished:         true

# SERVE
host:       0.0.0.0
livereload: true
port:       8080

