name: get-visitor-count
run-name: get-visitor-count run by ${{ github.actor }}
on: push # TODO: Change to schedule
jobs:
  get-visitor-count:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Run test.sh
        run: bash test.sh
        env:
          TEST_SECRET: ${{ vars.ACTIONS_RUNNER_DEBUG }}
      - name: Echo job status
        run: echo "job.status = ${{ job.status }}"
